image: gradle:7.0.1-jdk17

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_VERSION: $CI_COMMIT_SHORT_SHA
  DEPLOY_USER: deployer
  JAR_FILE: "$CI_PROJECT_DIR/core/build/libs/core-*.jar"
  CONFIG_FILE: "$CI_PROJECT_DIR/core/config/application.yml"
  DEPLOY_SERVER: mykid.ttc.software

default:
  services:
    - docker:dind
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

stages:
  - build
  - deploy


#deploy
build:
  stage: build
  script:
    - gradle clean build -x test
    - scp -o StrictHostKeyChecking=no $JAR_FILE $DEPLOY_USER@$DEPLOY_SERVER:/opt/fair/fair-core.jar
    - scp -o StrictHostKeyChecking=no $CONFIG_FILE $DEPLOY_USER@$DEPLOY_SERVER:/opt/fair/config/application.yml
  only:
    - develop
    - /^release*$/

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER '/opt/fair/run.sh && exit'
  only:
    - develop
    - /^release*$/
